name: Build and Publish Lambda Layer

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish-layer:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        aws-region: us-east-1


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies into Lambda Layer format
      run: |
        mkdir -p python
        pip install sentence-transformers -t python/

    - name: Zip the layer
      run: |
        zip -r sentence-transformers-layer.zip python

    - name: Publish Lambda Layer
      run: |
        aws lambda publish-layer-version \
          --layer-name sentence-transformers \
          --zip-file fileb://sentence-transformers-layer.zip \
          --compatible-runtimes python3.11 \
          --description "Layer with sentence-transformers"